import Navbar from "./components/Navbar";
import "./globals.css";
import Head from "next/head";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <Head>
                <title>OP66</title>
                <link href="/public/next.svg" />
            </Head>
            <body>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
